server:
  port: 5005

upload:
  path: /opt/file

spring:
  datasource:
    url: jdbc:mysql://172.21.22.9:3306/bet?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&allowMultiQueries=true
    username: root
    password: cloud123456
    driverClassName: com.mysql.cj.jdbc.Driver


mybatis:
  configuration:
    map-underscore-to-camel-case: true