server:
  port: 5005

upload:
  path: D:/file/tencent

spring:
  datasource:
    url: jdbc:mysql://152.136.130.252:3306/bet?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&allowMultiQueries=true
    username: root
    password: cloud123456
    driverClassName: com.mysql.cj.jdbc.Driver


mybatis:
  configuration:
    map-underscore-to-camel-case: true